"""
Linux behavioral signal profiles for the Lynx detection layer.

The Windows profiles in behavior_detector.py match Sysmon telemetry.
These profiles match Elastic Defend (ECS) Linux telemetry instead.

Field facts for the Linux pipeline:

- Process events land in index: logs-endpoint.events.process-*
  Fields used: process.name, process.args (list), process.executable,
  process.entity_id, process.parent.entity_id, event.action
- File events land in index: logs-endpoint.events.file-*
  Fields used: file.path, file.extension, process.name, event.action

Same rules as the Windows set: these are behavioral signals, not
precise detections. Substring matching, false positives expected on
benign admin work. Confidence reflects signal quality. The suppression
cap in behavior_detector.py applies to both platforms.
"""

LINUX_PROFILES = {

    # --- EXECUTION -----------------------------------------------------------

    "linux_bash_shell": {
        "names": ["bash", "sh", "dash"],
        "args_any": ["-c"],
        "technique": "T1059.004",
        "tactic": "EXECUTION",
        "description": "Shell Command Execution (bash -c)",
        "severity": "LOW",
        "priority_score": 30,
        "confidence": "low",
        "behavior_class": "execution",
    },
    "linux_python_exec": {
        "names": ["python3", "python", "python2"],
        "args_any": ["-c"],
        "technique": "T1059.006",
        "tactic": "EXECUTION",
        "description": "Python One-Liner Execution",
        "severity": "MEDIUM",
        "priority_score": 55,
        "confidence": "medium",
        "behavior_class": "execution",
    },
    "linux_curl_bash_pipe": {
        "names": ["bash", "sh", "curl"],
        "args_any": ["| bash", "| sh", "|bash", "|sh"],
        "technique": "T1059.004",
        "tactic": "EXECUTION",
        "description": "Remote Script Piped into Shell",
        "severity": "HIGH",
        "priority_score": 82,
        "confidence": "high",
        "behavior_class": "execution",
    },
    "linux_base64_decode": {
        "names": ["bash", "sh", "base64"],
        "args_any": ["base64 -d", "base64 --decode", "base64 -d "],
        "technique": "T1027",
        "tactic": "DEFENSE_EVASION",
        "description": "Base64 Decode in Shell",
        "severity": "MEDIUM",
        "priority_score": 60,
        "confidence": "medium",
        "behavior_class": "evasion",
    },
    "linux_curl_wget_download": {
        "names": ["curl", "wget"],
        "args_any": ["-o ", "-O ", "--output"],
        "technique": "T1105",
        "tactic": "EXECUTION",
        "description": "File Download via curl or wget",
        "severity": "MEDIUM",
        "priority_score": 55,
        "confidence": "medium",
        "behavior_class": "execution",
    },
    "linux_certutil_download": {
        "names": ["certutil"],
        "args_any": ["-urlcache", "-decode"],
        "technique": "T1105",
        "tactic": "EXECUTION",
        "description": "Certutil Download or Decode",
        "severity": "HIGH",
        "priority_score": 82,
        "confidence": "high",
        "behavior_class": "execution",
    },
    "linux_reverse_shell": {
        "names": ["nc", "ncat", "netcat", "socat"],
        "args_any": ["-e /bin", "-e /usr/bin", "-c bash", "-c sh"],
        "technique": "T1059.004",
        "tactic": "EXECUTION",
        "description": "Netcat or Socat Reverse Shell",
        "severity": "CRITICAL",
        "priority_score": 92,
        "confidence": "high",
        "behavior_class": "execution",
    },

    # --- PERSISTENCE ---------------------------------------------------------

    "linux_crontab_edit": {
        "names": ["crontab"],
        "args_any": ["-e", "-r"],
        "technique": "T1053.003",
        "tactic": "PERSISTENCE",
        "description": "Crontab Modified",
        "severity": "HIGH",
        "priority_score": 78,
        "confidence": "high",
        "behavior_class": "persistence",
    },
    "linux_cron_file_drop": {
        "file_paths": ["/etc/cron.d", "/etc/cron.daily", "/etc/cron.hourly", "/etc/crontab"],
        "technique": "T1053.003",
        "tactic": "PERSISTENCE",
        "description": "File Written to System Cron Directories",
        "severity": "HIGH",
        "priority_score": 82,
        "confidence": "high",
        "behavior_class": "persistence",
    },
    "linux_systemd_unit_create": {
        "file_paths": ["/etc/systemd/system", "/lib/systemd/system", "/usr/lib/systemd/system", ".config/systemd/user"],
        "file_exts": [".service", ".timer"],
        "technique": "T1543.002",
        "tactic": "PERSISTENCE",
        "description": "New Systemd Unit Created",
        "severity": "HIGH",
        "priority_score": 80,
        "confidence": "high",
        "behavior_class": "persistence",
    },
    "linux_systemctl_enable": {
        "names": ["systemctl"],
        "args_any": ["enable", "start"],
        "technique": "T1543.002",
        "tactic": "PERSISTENCE",
        "description": "Service Enabled via systemctl",
        "severity": "MEDIUM",
        "priority_score": 55,
        "confidence": "medium",
        "behavior_class": "persistence",
    },
    "linux_user_created": {
        "names": ["useradd", "adduser"],
        "technique": "T1136.001",
        "tactic": "PERSISTENCE",
        "description": "Local User Account Created",
        "severity": "HIGH",
        "priority_score": 85,
        "confidence": "high",
        "behavior_class": "persistence",
    },
    "linux_authorized_keys_write": {
        "file_paths": [".ssh/authorized_keys"],
        "technique": "T1098.004",
        "tactic": "PERSISTENCE",
        "description": "SSH Authorized Keys Modified",
        "severity": "CRITICAL",
        "priority_score": 92,
        "confidence": "high",
        "behavior_class": "persistence",
    },
    "linux_shell_config_write": {
        "file_paths": [".bashrc", ".bash_profile", ".profile", "/etc/profile.d"],
        "technique": "T1546.004",
        "tactic": "PERSISTENCE",
        "description": "Shell Configuration File Modified",
        "severity": "HIGH",
        "priority_score": 75,
        "confidence": "medium",
        "behavior_class": "persistence",
    },
    "linux_init_script_drop": {
        "file_paths": ["/etc/init.d"],
        "technique": "T1037.004",
        "tactic": "PERSISTENCE",
        "description": "Init Script Dropped",
        "severity": "HIGH",
        "priority_score": 78,
        "confidence": "high",
        "behavior_class": "persistence",
    },

    # --- DISCOVERY -----------------------------------------------------------

    "linux_whoami": {
        "names": ["whoami", "id"],
        "technique": "T1033",
        "tactic": "DISCOVERY",
        "description": "System Owner/User Discovery",
        "severity": "LOW",
        "priority_score": 20,
        "confidence": "low",
        "behavior_class": "recon",
    },
    "linux_system_info": {
        "names": ["uname", "lscpu", "hostnamectl", "hostname"],
        "technique": "T1082",
        "tactic": "DISCOVERY",
        "description": "System Information Discovery",
        "severity": "LOW",
        "priority_score": 20,
        "confidence": "low",
        "behavior_class": "recon",
    },
    "linux_network_config": {
        "names": ["ip", "ifconfig", "route"],
        "args_any": ["a", "addr", "-a", "route"],
        "technique": "T1016",
        "tactic": "DISCOVERY",
        "description": "Network Configuration Discovery",
        "severity": "LOW",
        "priority_score": 20,
        "confidence": "low",
        "behavior_class": "recon",
    },
    "linux_network_connections": {
        "names": ["ss", "netstat"],
        "technique": "T1049",
        "tactic": "DISCOVERY",
        "description": "Network Connections Discovery",
        "severity": "LOW",
        "priority_score": 20,
        "confidence": "low",
        "behavior_class": "recon",
    },
    "linux_process_discovery": {
        "names": ["ps"],
        "args_any": ["aux", "-ef", "fax"],
        "technique": "T1057",
        "tactic": "DISCOVERY",
        "description": "Process Discovery via ps",
        "severity": "LOW",
        "priority_score": 20,
        "confidence": "low",
        "behavior_class": "recon",
    },
    "linux_account_enum": {
        "names": ["cat", "getent", "grep"],
        "args_any": ["/etc/passwd", "/etc/group", "passwd", "group"],
        "technique": "T1087.001",
        "tactic": "DISCOVERY",
        "description": "Local Account Enumeration",
        "severity": "MEDIUM",
        "priority_score": 45,
        "confidence": "medium",
        "behavior_class": "recon",
    },
    "linux_sudo_list": {
        "names": ["sudo"],
        "args_any": ["-l"],
        "technique": "T1548.003",
        "tactic": "PRIVILEGE_ESCALATION",
        "description": "Sudo Rights Enumeration",
        "severity": "MEDIUM",
        "priority_score": 50,
        "confidence": "medium",
        "behavior_class": "recon",
    },
    "linux_file_discovery": {
        "names": ["find"],
        "args_any": ["-perm", "-name", "/ -type"],
        "technique": "T1083",
        "tactic": "DISCOVERY",
        "description": "File and Directory Discovery via find",
        "severity": "LOW",
        "priority_score": 25,
        "confidence": "low",
        "behavior_class": "recon",
    },
    "linux_ping_sweep": {
        "names": ["ping"],
        "args_any": ["-c 1", "-c1"],
        "technique": "T1018",
        "tactic": "DISCOVERY",
        "description": "Remote System Discovery via Ping",
        "severity": "LOW",
        "priority_score": 25,
        "confidence": "low",
        "behavior_class": "recon",
    },
    "linux_tcpdump": {
        "names": ["tcpdump", "tshark"],
        "technique": "T1040",
        "tactic": "DISCOVERY",
        "description": "Packet Capture via tcpdump",
        "severity": "MEDIUM",
        "priority_score": 60,
        "confidence": "medium",
        "behavior_class": "recon",
    },
    "linux_nmap": {
        "names": ["nmap"],
        "technique": "T1046",
        "tactic": "DISCOVERY",
        "description": "Network Scan via nmap",
        "severity": "MEDIUM",
        "priority_score": 60,
        "confidence": "high",
        "behavior_class": "recon",
    },

    # --- CREDENTIAL ACCESS ---------------------------------------------------

    "linux_shadow_read": {
        "names": ["cat", "grep", "less", "head"],
        "args_any": ["/etc/shadow"],
        "technique": "T1003.008",
        "tactic": "CREDENTIAL_ACCESS",
        "description": "Read of /etc/shadow",
        "severity": "CRITICAL",
        "priority_score": 95,
        "confidence": "high",
        "behavior_class": "credential_access",
    },
    "linux_mimipenguin": {
        "names": ["mimipenguin"],
        "technique": "T1003.007",
        "tactic": "CREDENTIAL_ACCESS",
        "description": "Mimipenguin Credential Dumping",
        "severity": "CRITICAL",
        "priority_score": 95,
        "confidence": "high",
        "behavior_class": "credential_access",
    },
    "linux_ptrace_attach": {
        "names": ["gdb", "strace", "ltrace"],
        "args_any": ["-p"],
        "technique": "T1055.008",
        "tactic": "PRIVILEGE_ESCALATION",
        "description": "Process Injection via ptrace Attach",
        "severity": "HIGH",
        "priority_score": 85,
        "confidence": "medium",
        "behavior_class": "credential_access",
    },
    "linux_history_dump": {
        "names": ["cat", "grep", "less"],
        "args_any": [".bash_history", ".zsh_history"],
        "technique": "T1552.003",
        "tactic": "CREDENTIAL_ACCESS",
        "description": "Shell History Read",
        "severity": "MEDIUM",
        "priority_score": 55,
        "confidence": "medium",
        "behavior_class": "credential_access",
    },
    "linux_ssh_key_read": {
        "names": ["cat", "grep", "less"],
        "args_any": ["id_rsa", "id_ed25519", ".ssh/"],
        "technique": "T1552.004",
        "tactic": "CREDENTIAL_ACCESS",
        "description": "Private SSH Key Read",
        "severity": "HIGH",
        "priority_score": 80,
        "confidence": "high",
        "behavior_class": "credential_access",
    },

    # --- DEFENSE EVASION -----------------------------------------------------

    "linux_firewall_disable": {
        "names": ["ufw", "iptables", "firewalld"],
        "args_any": ["disable", "-F", "--flush"],
        "technique": "T1562.004",
        "tactic": "DEFENSE_EVASION",
        "description": "Firewall Disabled or Flushed",
        "severity": "CRITICAL",
        "priority_score": 92,
        "confidence": "high",
        "behavior_class": "evasion",
    },
    "linux_selinux_disable": {
        "names": ["setenforce"],
        "args_any": ["0"],
        "technique": "T1562.001",
        "tactic": "DEFENSE_EVASION",
        "description": "SELinux Set to Permissive",
        "severity": "CRITICAL",
        "priority_score": 92,
        "confidence": "high",
        "behavior_class": "evasion",
    },
    "linux_security_service_stop": {
        "names": ["systemctl", "service"],
        "args_any": ["stop auditd", "stop apparmor", "stop fail2ban", "stop ufw", "disable auditd"],
        "technique": "T1562.001",
        "tactic": "DEFENSE_EVASION",
        "description": "Security Service Stopped",
        "severity": "CRITICAL",
        "priority_score": 92,
        "confidence": "high",
        "behavior_class": "evasion",
    },
    "linux_hidden_file": {
        "names": ["mv", "cp"],
        "args_any": ["/.", "/."],
        "technique": "T1564.001",
        "tactic": "DEFENSE_EVASION",
        "description": "File Hidden as Dotfile",
        "severity": "LOW",
        "priority_score": 30,
        "confidence": "low",
        "behavior_class": "evasion",
    },
    "linux_chattr": {
        "names": ["chattr"],
        "technique": "T1222.002",
        "tactic": "DEFENSE_EVASION",
        "description": "File Attributes Modified via chattr",
        "severity": "MEDIUM",
        "priority_score": 50,
        "confidence": "medium",
        "behavior_class": "evasion",
    },
    "linux_log_cleanup": {
        "names": ["rm", "journalctl", "truncate"],
        "args_any": ["/var/log", "--vacuum", "vacuum-size", "-s 0"],
        "technique": "T1070.002",
        "tactic": "DEFENSE_EVASION",
        "description": "Log Files Deleted or Vacuumed",
        "severity": "HIGH",
        "priority_score": 85,
        "confidence": "high",
        "behavior_class": "evasion",
    },
    "linux_history_clear": {
        "names": ["history", "shred", "rm"],
        "args_any": ["-c", ".bash_history"],
        "technique": "T1070.003",
        "tactic": "DEFENSE_EVASION",
        "description": "Shell History Cleared",
        "severity": "MEDIUM",
        "priority_score": 55,
        "confidence": "medium",
        "behavior_class": "evasion",
    },

    # --- COLLECTION AND EXFILTRATION -----------------------------------------

    "linux_archive_files": {
        "names": ["tar", "zip", "7z", "gzip"],
        "args_any": ["-czf", "-cf", "-r", "-a"],
        "technique": "T1560.001",
        "tactic": "COLLECTION",
        "description": "Files Archived for Collection",
        "severity": "MEDIUM",
        "priority_score": 55,
        "confidence": "low",
        "behavior_class": "collection",
    },
    "linux_curl_upload": {
        "names": ["curl", "wget"],
        "args_any": ["-T ", "--upload-file", "--post-file"],
        "technique": "T1048",
        "tactic": "EXFILTRATION",
        "description": "Curl or Wget Outbound Data Transfer",
        "severity": "HIGH",
        "priority_score": 80,
        "confidence": "medium",
        "behavior_class": "exfiltration",
    },

    # --- IMPACT --------------------------------------------------------------

    "linux_rm_rf": {
        "names": ["rm"],
        "args_any": ["-rf /", "-fr /", "--no-preserve-root"],
        "technique": "T1485",
        "tactic": "IMPACT",
        "description": "Recursive Delete of Filesystem",
        "severity": "CRITICAL",
        "priority_score": 95,
        "confidence": "high",
        "behavior_class": "impact",
    },
    "linux_dd_destruction": {
        "names": ["dd"],
        "args_any": ["of=/dev/sd", "of=/dev/disk"],
        "technique": "T1485",
        "tactic": "IMPACT",
        "description": "Disk Overwrite via dd",
        "severity": "CRITICAL",
        "priority_score": 95,
        "confidence": "high",
        "behavior_class": "impact",
    },
    "linux_shutdown": {
        "names": ["shutdown", "reboot", "poweroff", "init"],
        "args_any": ["-h now", "now", "0", "6"],
        "technique": "T1529",
        "tactic": "IMPACT",
        "description": "System Shutdown or Reboot",
        "severity": "LOW",
        "priority_score": 25,
        "confidence": "low",
        "behavior_class": "impact",
    },
    "linux_binary_dropped_tmp": {
        "file_paths": ["/tmp", "/var/tmp", "/dev/shm"],
        "technique": "T1105",
        "tactic": "EXECUTION",
        "description": "Binary Dropped in Temp Location",
        "severity": "HIGH",
        "priority_score": 75,
        "confidence": "medium",
        "behavior_class": "execution",
    },
}

LINUX_PROCESS_INDEX = "logs-endpoint.events.process-*"
LINUX_FILE_INDEX = "logs-endpoint.events.file-*"
